from __future__ import annotations

from typing import Protocol, Sequence


class StorageBackend(Protocol):
    def init(self) -> None: ...
    def create_persona(self, user_id: str, persona_id: str, display_name: str | None, description: str | None) -> None: ...
    def get_persona(self, user_id: str, persona_id: str) -> dict | None: ...
    def append_message(self, data: dict) -> int: ...
    def recent_messages(self, user_id: str, persona_id: str, limit: int, days: int | None) -> list[dict]: ...
    def purge_messages(self, user_id: str, persona_id: str, before_ts: int | None) -> int: ...
    def write_memory(self, data: dict) -> tuple[bool, int]: ...
    def list_memory(self, user_id: str, persona_id: str) -> list[dict]: ...
    def recall_memory(self, user_id: str, persona_id: str, query: str, limit: int) -> list[dict]: ...
    def forget_memory(self, user_id: str, persona_id: str, mtype: str, key: str) -> int: ...
    def confirm_memory(self, user_id: str, persona_id: str, memory_id: int, supersedes_id: int | None = None) -> dict | None: ...
    def revoke_memory(self, user_id: str, persona_id: str, memory_id: int) -> dict | None: ...
    def get_memory_by_id(self, user_id: str, persona_id: str, memory_id: int) -> dict | None: ...
    def rebuild_fts(self, user_id: str, persona_id: str) -> None: ...
    def metrics(self) -> dict: ...
    def fts_enabled(self) -> bool: ...
    def get_slots(self, user_id: str, persona_id: str) -> list[dict]: ...
    def set_slot(self, user_id: str, persona_id: str, slot_name: str, value_json: str, provenance_json: str | None) -> None: ...
    def create_goal(self, user_id: str, persona_id: str, title: str, details: str | None) -> int: ...
    def list_goals(self, user_id: str, persona_id: str) -> list[dict]: ...
    def update_goal_status(self, user_id: str, persona_id: str, goal_id: int, status: str) -> int: ...
    def link_goal(self, user_id: str, persona_id: str, goal_id: int, memory_id: int | None, note: str | None) -> int | None: ...


class RecallEngine(Protocol):
    def recall(self, user_id: str, persona_id: str, query: str, limit: int) -> dict: ...


class JudgeEngine(Protocol):
    def judge(self, payload: dict) -> dict: ...


class ProfileBuilder(Protocol):
    def build(self, persona: dict | None, memory_items: Sequence[dict]) -> str: ...


class SensitivePolicy(Protocol):
    def check(self, text: str) -> tuple[bool, str | None]: ...


class EventSink(Protocol):
    def emit(self, event: str, payload: dict) -> None: ...
